version: '3'

services:
  nginx:
    restart: always
    image: nginx:stable-alpine
    command: [nginx, '-g', 'daemon off;']
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - web-backend
      - app-backend
    networks:
      - mypath-link

  web:
    restart: always
    image: us-east5-docker.pkg.dev/wheelshare-webapp/wheelshare/web:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
    networks:
      - mypath-link
      
  web-backend:
    restart: always
    image: us-east5-docker.pkg.dev/wheelshare-webapp/wheelshare/web-backend:latest
    volumes:
      - ./firebase-key.json:/app/firebase-key.json
    networks:
      - mypath-link

networks:
  mypath-link: